name: Deploy Python Lambda

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./env/homolog

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar AWS credenciais via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Inicializar Terraform
        working-directory: ./env/homolog
        run: terraform init

      - name: Aplicar Terraform (Deploy Lambda)
        id: apply
        working-directory: ./env/homolog
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          TF_VAR_verified_email: '${{ secrets.VERIFIED_EMAIL }}'
        run: terraform apply -auto-approve
